modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="aaaoab"
version="Beta 1.0.0"
displayName="An Approximate Amount Of Appropriate Biomes"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Shadowdragon019, MCreator"
description='''
To add a bunch of biomes
'''

[[dependencies.aaaoab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




